# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update Hugo via Go modules (if applicable)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Optionally, specify allowed or ignored dependencies
    # allow:
    #   - dependency-type: "direct"
    #   - dependency-type: "indirect"

  # Update npm dependencies (if your project uses package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Update Docker dependencies (if using a Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Add more package ecosystems if needed
  # For example, if using Ruby's Bundler:
  # - package-ecosystem: "bundler"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"

# Optional: Configure security updates separately if desired
# By default, security updates are enabled

