baseURL = "https://github.com/rimubytes"
relativeURLs = true
languageCode = "en-us"
title = "Marvin Murithi | Site Reliability Engineer"
paginate = 3
theme = "maverick"

[permalinks]
  blog = "/blog/:year/:month/:title/"
  portfolio = "/portfolio/:slug/"

[params]
  logo = "/assets/favicon.ico"
  description = "Software engineer with a thrill for infrastructure"
  author = "Marvin Murithi"

  [params.comments]
    enabled = true
    githubRepo = "yourusername/yourrepo"
    theme = "github-light"

  # Footer Rights
  footerRights = "© 2024 Marvin Murithi. All rights reserved."

  # Social Links
  socialLinks = [
    { name = "LinkedIn", url = "https://www.linkedin.com/in/marvin-m-249088179/", icon = "linkedin" },
    { name = "GitHub", url = "https://github.com/rimubytes", icon = "github" },
    { name = "Email", url = "mailto:murithimarvin09@gmail.com", icon = "envelope" }
  ]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2

  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"
    weight = 3

  [[menu.main]]
    identifier = "papershelf"
    name = "Papershelf"
    url = "/papershelf/"
    weight = 4
    
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    hl_inline = false
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = "monokailight"
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
